export enum TipoPagamento {
	BOLETO = "BOLETO",
	CARTAO = "CARTAO",
	CONTA = "CONTA_ANDARIO",
	DEBITO = "DEBITO",
	POS = "POS",
	DEPOSITO = "DEPOSITO",
	TRANSFERENCIA = "TRANSFERENCIA",
	GRATUITO = "GRATUITO"
}

